# Generated by Django 4.1.3 on 2022-12-22 00:20

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("menus", "0002_menuitem_uuid"),
        ("orders", "0002_order_uuid_menuitemquantity_cart_order_items"),
    ]

    operations = [
        migrations.CreateModel(
            name="CartMenuItemQuantity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, verbose_name="uuid"
                    ),
                ),
                ("quantity", models.IntegerField(verbose_name="quantity")),
            ],
        ),
        migrations.CreateModel(
            name="OrderMenuItemQuantity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, verbose_name="uuid"
                    ),
                ),
                ("quantity", models.IntegerField(verbose_name="quantity")),
                (
                    "item",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="menus.menuitem",
                    ),
                ),
            ],
        ),
        migrations.RemoveField(
            model_name="cart",
            name="items",
        ),
        migrations.RemoveField(
            model_name="order",
            name="items",
        ),
        migrations.AlterField(
            model_name="order",
            name="placement_date",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.DeleteModel(
            name="MenuItemQuantity",
        ),
        migrations.AddField(
            model_name="ordermenuitemquantity",
            name="order",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="orders.order",
            ),
        ),
        migrations.AddField(
            model_name="cartmenuitemquantity",
            name="cart",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="orders.cart",
            ),
        ),
        migrations.AddField(
            model_name="cartmenuitemquantity",
            name="item",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="menus.menuitem",
            ),
        ),
    ]
