# Generated by Django 4.1.3 on 2022-12-24 13:12

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("restaurants", "0004_restaurant_uuid"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("orders", "0004_order_order_time"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="owner",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="price",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("0.00"), max_digits=10
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="restaurants",
            field=models.ManyToManyField(to="restaurants.restaurant"),
        ),
    ]
