# Generated by Django 4.1.3 on 2022-12-28 21:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("geo", "0002_location_useraddress_location"),
        ("orders", "0007_order_address"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="location",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="geo.location",
            ),
        ),
    ]
