# Generated by Django 4.1.3 on 2023-01-28 14:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("geo", "0003_route_routelocation"),
        ("orders", "0009_order_active"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="restaurant_to_destination",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="geo.route",
            ),
        ),
    ]
