# Generated by Django 4.1.3 on 2023-01-28 16:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0010_order_restaurant_to_destination"),
        ("geo", "0003_route_routelocation"),
        ("driver", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="driver",
            name="active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="driver",
            name="home_location",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="geo.location",
            ),
        ),
        migrations.CreateModel(
            name="DriverOrder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "driver_to_restaurant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="geo.route",
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="orders.order",
                    ),
                ),
            ],
        ),
        migrations.AlterField(
            model_name="driver",
            name="accepted",
            field=models.ManyToManyField(
                related_name="driver_accepted", to="driver.driverorder"
            ),
        ),
        migrations.AlterField(
            model_name="driver",
            name="declined",
            field=models.ManyToManyField(
                related_name="driver_declined", to="driver.driverorder"
            ),
        ),
        migrations.AlterField(
            model_name="driver",
            name="recommended",
            field=models.ManyToManyField(
                related_name="driver_recommended", to="driver.driverorder"
            ),
        ),
    ]
