# Generated by Django 4.1.3 on 2023-01-25 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("driver", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="driver",
            name="active",
            field=models.BooleanField(default=True),
        ),
    ]
