# Generated by Django 4.1.3 on 2023-01-28 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("driver", "0002_driver_active_driver_home_location_driverorder_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="driver",
            name="accepted",
        ),
        migrations.RemoveField(
            model_name="driver",
            name="declined",
        ),
        migrations.RemoveField(
            model_name="driver",
            name="recommended",
        ),
    ]
