# Generated by Django 4.1.3 on 2023-01-28 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("driver", "0003_remove_driver_accepted_remove_driver_declined_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="driver",
            name="accepted",
            field=models.ManyToManyField(
                related_name="driver_accepted", to="driver.driverorder"
            ),
        ),
        migrations.AddField(
            model_name="driver",
            name="declined",
            field=models.ManyToManyField(
                related_name="driver_declined", to="driver.driverorder"
            ),
        ),
        migrations.AddField(
            model_name="driver",
            name="recommended",
            field=models.ManyToManyField(
                related_name="driver_recommended", to="driver.driverorder"
            ),
        ),
    ]
