# Generated by Django 4.1.3 on 2023-01-28 17:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0010_order_restaurant_to_destination"),
        ("driver", "0004_driver_accepted_driver_declined_driver_recommended"),
    ]

    operations = [
        migrations.AlterField(
            model_name="driverorder",
            name="order",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="orders.order",
            ),
        ),
    ]
