# Generated by Django 4.1.3 on 2022-12-18 16:32

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("restaurants", "0003_restaurant_owner"),
    ]

    operations = [
        migrations.AddField(
            model_name="restaurant",
            name="uuid",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, verbose_name="uuid"
            ),
        ),
    ]
