# Generated by Django 4.1.3 on 2022-12-23 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="address",
            name="country",
            field=models.CharField(
                default="Canada", max_length=30, verbose_name="country"
            ),
        ),
        migrations.AddField(
            model_name="address",
            name="unit",
            field=models.CharField(default="", max_length=100, verbose_name="unit"),
        ),
    ]
