# Generated by Django 4.1.3 on 2022-12-23 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0002_address_country_address_unit"),
    ]

    operations = [
        migrations.AlterField(
            model_name="address",
            name="postal_code",
            field=models.CharField(max_length=10, verbose_name="postal code"),
        ),
    ]
