# Generated by Django 4.1.3 on 2022-12-14 23:19

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("menus", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="menuitem",
            name="uuid",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, verbose_name="uuid"
            ),
        ),
    ]
