# Generated by Django 4.1.3 on 2022-12-28 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("menus", "0003_alter_menuitem_price"),
    ]

    operations = [
        migrations.AlterField(
            model_name="menuitem",
            name="description",
            field=models.CharField(
                blank=True, default="", max_length=500, verbose_name="description"
            ),
        ),
    ]
